language: node_js

node_js:
  - 12
  - 14
  - 16
  - 19

install:
  - npm install

before_script:
  - openssl aes-256-cbc -K $encrypted_2be0a157b4e7_key -iv $encrypted_2be0a157b4e7_iv -in service-account.json.enc -out service-account.json -d

script:
  - npm run lint
  - npm test
  - npm run build
  - npm run docs

deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release