language: node_js

node_js:
  - 8
  - 6

stages:
  - lint
  - test
  - build
  - docs
  - release

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      before_script:
        # Decrypt service account file
        - openssl aes-256-cbc -K $encrypted_2be0a157b4e7_key -iv $encrypted_2be0a157b4e7_iv -in service-account.json.enc -out service-account.json -d
      script:
        - npm test
    - stage: build
      script:
        - npm run build
    - stage: docs
      script:
        - npm run docs
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          # Decrypt service account file
          - openssl aes-256-cbc -K $encrypted_2be0a157b4e7_key -iv $encrypted_2be0a157b4e7_iv -in service-account.json.enc -out service-account.json -d
        script:
          - npx semantic-release